# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen_g', models.FileField(max_length=20, upload_to=b'')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nana.fecha')),
            ],
        ),
    ]
